ICON_MIMETYPE_BLACKLIST = [
  'application/xml',
  'text/html',
  'text/plain',
]

MIN_ICON_LENGTH = 100
MAX_ICON_LENGTH = 20000

MC_CACHE_TIME = 2419200 # seconds (28 days)

DEFAULT_FAVICON_LOC =
DEFAULT_FAVICON_TYPE =

CONNECTION_TIMEOUT = 5
TIMEOUT = 10
